# AprilTag 3 code parameters
# Find descriptions in apriltag/include/apriltag.h:struct apriltag_detector
#                      apriltag/include/apriltag.h:struct apriltag_family
tag_family:        'tag25h9' # options: tag36h11, tag25h9, tag16h5
tag_threads:       2          # default: 2
tag_decimate:      1.0        # default: 1.0
tag_blur:          0.1        # default: 0.0
tag_refine_edges:  1          # default: 1
tag_debug:         0          # default: 0
tag_refine_decode: 10          # default: 0
tag_border:        1  
tag_refine_pose:   10     
# Other parameters
publish_tf:        false       # default: false
publish_tag_detections_image: true
