# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 1.0
joint_1:
  ID: 1
  Return_Delay_Time: 0
  Max_Position_Limit: 303750
  Min_Position_Limit: -303750
  Velocity_Limit: 250
joint_2:
  ID: 2
  Return_Delay_Time: 0
  Max_Position_Limit: 175000
  Min_Position_Limit: -175000
  Velocity_Limit: 750
joint_3:
  ID: 3
  Return_Delay_Time: 0
  Max_Position_Limit: 228000
  Min_Position_Limit: -228000
  Velocity_Limit: 350
joint_4:
  ID: 4
  Return_Delay_Time: 0
  Max_Position_Limit: 4095
  Min_Position_Limit: 0
  Velocity_Limit: 3
joint_5:
  ID: 5
  Return_Delay_Time: 0
  Max_Position_Limit: 3312
  Min_Position_Limit: 782
  Velocity_Limit: 3
joint_6:
  ID: 6
  Return_Delay_Time: 0
  Max_Position_Limit: 4095
  Min_Position_Limit: 0
  Velocity_Limit: 3
